"""add max_task_workers to settings

Revision ID: 5dfa7ab1a5bb
Revises: cfb3da8d1ed7
Create Date: 2026-01-08 10:27:35.998055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfa7ab1a5bb'
down_revision = 'cfb3da8d1ed7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 注释掉 SQLite 不支持的外键操作
    # op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('settings', sa.Column('max_task_workers', sa.Integer(), nullable=False, server_default='4'))
    # op.create_foreign_key(None, 'users', 'membership_plans', ['current_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('settings', 'max_task_workers')
    # op.drop_constraint(None, 'projects', type_='foreignkey')
    # ### end Alembic commands ###



