"""add membership system tables

Revision ID: 984f4a0521a8
Revises: 98c19e842a30
Create Date: 2025-12-30 18:54:47.158645

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
import uuid


# revision identifiers, used by Alembic.
revision = '984f4a0521a8'
down_revision = '98c19e842a30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feature_code', sa.String(length=50), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('min_level', sa.String(length=20), nullable=False),
    sa.Column('consume_quota', sa.Boolean(), nullable=True),
    sa.Column('quota_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_permissions_feature_code'), 'feature_permissions', ['feature_code'], unique=True)
    op.create_table('membership_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('image_quota', sa.Integer(), nullable=True),
    sa.Column('premium_quota', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_plans_level'), 'membership_plans', ['level'], unique=False)
    # 注释掉 SQLite 不支持的外键操作
    # op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    # op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('membership_level', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('membership_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('current_plan_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('image_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('premium_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('quota_reset_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_membership_level'), 'users', ['membership_level'], unique=False)
    # op.create_foreign_key(None, 'users', 'membership_plans', ['current_plan_id'], ['id'])
    # ### end Alembic commands ###

    # 插入默认套餐数据
    now = datetime.utcnow()
    membership_plans = sa.table(
        'membership_plans',
        sa.column('id', sa.String),
        sa.column('name', sa.String),
        sa.column('level', sa.String),
        sa.column('period_type', sa.String),
        sa.column('duration_days', sa.Integer),
        sa.column('price', sa.Numeric),
        sa.column('image_quota', sa.Integer),
        sa.column('premium_quota', sa.Integer),
        sa.column('is_active', sa.Boolean),
        sa.column('is_default', sa.Boolean),
        sa.column('sort_order', sa.Integer),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    op.bulk_insert(membership_plans, [
        # 免费套餐（默认）
        {'id': str(uuid.uuid4()), 'name': '免费用户', 'level': 'free', 'period_type': 'none',
         'duration_days': 0, 'price': 0, 'image_quota': 10, 'premium_quota': 0,
         'is_active': True, 'is_default': True, 'sort_order': 0, 'created_at': now, 'updated_at': now},
        # 基础月度
        {'id': str(uuid.uuid4()), 'name': '基础月度', 'level': 'basic', 'period_type': 'monthly',
         'duration_days': 30, 'price': 19.9, 'image_quota': 100, 'premium_quota': 0,
         'is_active': True, 'is_default': False, 'sort_order': 1, 'created_at': now, 'updated_at': now},
        # 基础年度
        {'id': str(uuid.uuid4()), 'name': '基础年度', 'level': 'basic', 'period_type': 'yearly',
         'duration_days': 365, 'price': 169, 'image_quota': 1500, 'premium_quota': 0,
         'is_active': True, 'is_default': False, 'sort_order': 2, 'created_at': now, 'updated_at': now},
        # 高级月度
        {'id': str(uuid.uuid4()), 'name': '高级月度', 'level': 'premium', 'period_type': 'monthly',
         'duration_days': 30, 'price': 49.9, 'image_quota': 500, 'premium_quota': 50,
         'is_active': True, 'is_default': False, 'sort_order': 3, 'created_at': now, 'updated_at': now},
        # 高级年度
        {'id': str(uuid.uuid4()), 'name': '高级年度', 'level': 'premium', 'period_type': 'yearly',
         'duration_days': 365, 'price': 399, 'image_quota': 8000, 'premium_quota': 800,
         'is_active': True, 'is_default': False, 'sort_order': 4, 'created_at': now, 'updated_at': now},
    ])

    # 插入默认功能权限配置
    feature_permissions = sa.table(
        'feature_permissions',
        sa.column('id', sa.String),
        sa.column('feature_code', sa.String),
        sa.column('feature_name', sa.String),
        sa.column('min_level', sa.String),
        sa.column('consume_quota', sa.Boolean),
        sa.column('quota_type', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    op.bulk_insert(feature_permissions, [
        # 生成图片 - 所有用户可用，消耗图片配额
        {'id': str(uuid.uuid4()), 'feature_code': 'generate_image', 'feature_name': '生成PPT图片',
         'min_level': 'free', 'consume_quota': True, 'quota_type': 'image',
         'is_active': True, 'created_at': now, 'updated_at': now},
        # 导出图片PPTX - 所有用户可用
        {'id': str(uuid.uuid4()), 'feature_code': 'export_image_pptx', 'feature_name': '导出图片PPTX',
         'min_level': 'free', 'consume_quota': False, 'quota_type': None,
         'is_active': True, 'created_at': now, 'updated_at': now},
        # 导出PDF - 所有用户可用
        {'id': str(uuid.uuid4()), 'feature_code': 'export_pdf', 'feature_name': '导出PDF',
         'min_level': 'free', 'consume_quota': False, 'quota_type': None,
         'is_active': True, 'created_at': now, 'updated_at': now},
        # 导出可编辑PPTX - 仅高级会员，消耗高级配额
        {'id': str(uuid.uuid4()), 'feature_code': 'export_editable_pptx', 'feature_name': '导出可编辑PPTX',
         'min_level': 'premium', 'consume_quota': True, 'quota_type': 'premium',
         'is_active': True, 'created_at': now, 'updated_at': now},
        # PDF转可编辑PPTX - 仅高级会员，消耗高级配额
        {'id': str(uuid.uuid4()), 'feature_code': 'pdf_to_pptx', 'feature_name': 'PDF转可编辑PPTX',
         'min_level': 'premium', 'consume_quota': True, 'quota_type': 'premium',
         'is_active': True, 'created_at': now, 'updated_at': now},
        # 下载导出文件 - 所有用户可用
        {'id': str(uuid.uuid4()), 'feature_code': 'download', 'feature_name': '下载导出文件',
         'min_level': 'free', 'consume_quota': False, 'quota_type': None,
         'is_active': True, 'created_at': now, 'updated_at': now},
    ])

    # 更新现有用户的会员等级为 free，并设置默认配额
    op.execute("UPDATE users SET membership_level = 'free', image_quota = 10 WHERE membership_level IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_membership_level'), table_name='users')
    op.drop_column('users', 'quota_reset_at')
    op.drop_column('users', 'premium_quota')
    op.drop_column('users', 'image_quota')
    op.drop_column('users', 'current_plan_id')
    op.drop_column('users', 'membership_expires_at')
    op.drop_column('users', 'membership_level')
    # op.drop_constraint(None, 'projects', type_='foreignkey')
    # op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_index(op.f('ix_membership_plans_level'), table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_index(op.f('ix_feature_permissions_feature_code'), table_name='feature_permissions')
    op.drop_table('feature_permissions')
    # ### end Alembic commands ###



